@startuml "Consulta de cuotas"

actor User
boundary "Rest\nAPI" as API
control "Guessing\nInstallments" as GI
entity "Global\nSettings" as GB
entity "Credit\nStructure" as CS
control "GetCredit\nBalance" as GCB



activate User
User->API: 1. GET /credits/v1/{product}/{loan_type}/options/{amount}
activate API
API->GI: 2. Guess installments
activate GI
GI->GI: 3. Validate {loan_type}\nfor {product}
activate GI
GI-->GI: //error//
deactivate GI

opt error
    GI-->API: //Invalid {loan_type}//\n//for {product}//
    API-->User: //Invalid {loan_type}//\n//for {product}//
end

GI->GB: 4. Get minimum amount for {loan_type}
activate GB
GB-->GI: //minimum//
deactivate GB
opt amount < minimum
    GI-->API: //Invalid {amount}//\n//for {loan_type}//
    API-->User: //Invalid {amount}//\n//for {loan_type}//
end

GI->CS: 5. Find credit option by {amount}
activate CS
CS-->GI: //credit option//
deactivate CS
opt credit option = null
    GI-->API: //No options//\n//for {amount}//
    API-->User: //No options//\n//for {amount}//
end

GI->GCB: 6. Get client credit balance
activate GCB
create entity "Credit\nBalance" as CB
GCB->CB: Create
GCB-->GI: //balace//
deactivate GCB

GI->CB: 7. Get score
activate CB
CB-->GI: //score//
deactivate CB

opt score == 0
    GI-->API: //No options//\n//for {amount}//
    API-->User: //No options//\n//for {amount}//
end

GI->CB: 8. Is valid ?
activate CB
CB-->GI: //is valid//
deactivate CB

opt ! is valid
    GI-->API: //No options//\n//for {amount}//
    API-->User: //No options//\n//for {amount}//
end

GI->CB: 9. Get remaining amount
activate CB
CB-->GI: //remaining//
deactivate CB

opt remaining < amount
    GI-->API: //No options//\n//for {amount}//
    API-->User: //No options//\n//for {amount}//
end




@enduml